# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Graph-Layderer
version:      0.03
version_from: lib/Graph/Layouter.pm
installdirs:  site
requires:
    Graph:                         0
    Imager:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
